### PR TITLE
Support mtx(Matrix Market) file format as input

### PR DESCRIPTION
**Pull request by CharleneZ95**
Dear CellPhoneDB Team,
Since writing a large dataset to txt is a time-consuming task, see #138.
I added a functionality to load `.mtx` (Matrix Market) file.
#### Example using .mtx as input:
```sh
cellphonedb method statistical_analysis test_meta.txt input_dir
```
Where `input_dir` is the directory containing the ***matrix.mtx, features.tsv,*** and ***barcodes.tsv*** files.
#### Using following code to generate input files in R:
```R
library(Matrix)

expr_data <- as(as.matrix(expr_data), 'dgCMatrix')
features <- rownames(expr_data)
barcodes <- colnames(expr_data)

# output to file
writeLines(features, file = 'features.tsv')
writeLines(barcodes, file = 'barcodes.tsv')
writeMM(expr_data, file='matrix.mtx')
```
Where `expr_data` is the data matrix with row (genes) and column (cells) labels.

### CODE REVIEW

**Comment by dbrookeUAB** [comment]
The hero we deserve. This really needs to be implemented into the main branch. Text files are not sustainable.

**Comment by maxim-h** [comment]
Looks like the project is completely dead, which is a shame. Maybe someone will have the time to maintain an up-to-date fork in the future.

**Comment by stela2502** [comment]
Just a simple correction:
The lines like 
`writeLines(features, file = 'features.tsv')`
need to look like this:
`writeLines(features, con= 'features.tsv')`

**Comment by prete** [comment]
Merged and fixed in #264

**Pull request closed without merging**
